# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fipe_MVVM_' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyJSON'

  # Pods for Fipe_MVVM_

  target 'Fipe_MVVM_Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Fipe_MVVM_UITests' do
    # Pods for testing
  end

end
